avatar done
ashifkhn/component-library pull request #1
Opened 2022-02-01 06:00 UTC by ashifkhn

2022-02-01 06:14 UTC, Pratham82 reviewed
- Mention the avatar size classes in the description.
- Align code in the center
- Add left padding to the sidebar
- Vertically align the content in the navbar using `align-items`

2022-02-01 20:27 UTC, sakshi006 commented on components/Badge/badge.html
> +<html lang="en">
You can add some styling to the badges as well. Try to make them cover a part of the image. Add different background to highlight a badge.

2022-02-01 20:28 UTC, sakshi006 reviewed
Requested changes

2022-02-02 07:41 UTC, sakshi006 commented on components/Badge/styleBadge.css
> +    padding: 7px;
` padding: 3px 7px 12px 7px;`

2022-02-02 07:42 UTC, sakshi006 commented on components/Badge/styleBadge.css
> +    top: -1rem;
` top: -0.4rem;
    left: -0.7rem;
`

2022-02-02 07:43 UTC, sakshi006 commented on components/Badge/styleBadge.css
> +    top: -4rem;
`
top: -3.5rem;
    right: 1.5rem;
`

2022-02-02 07:43 UTC, sakshi006 commented on components/Badge/styleBadge.css
> +    padding: 7px;
` padding: 2px 8px 2px 8px `

2022-02-02 07:46 UTC, sakshi006 commented on components/Badge/styleBadge.css
> +    top: -6rem;
` top: -4.5rem;
    right: 1.5rem; `

2022-02-02 07:46 UTC, sakshi006 commented on components/Badge/styleBadge.css
> +    padding: 7px;
` padding: 2px 8px 2px 8px; `

2022-02-02 07:48 UTC, sakshi006 commented on components/Badge/styleBadge.css
> +    padding: 7px;
` padding: 2px 8px 2px 8px; `

2022-02-02 07:49 UTC, sakshi006 commented on components/Badge/styleBadge.css
> +    top: -5rem;
` top: -4.5rem;
    right: 1.5rem; `

2022-02-02 07:49 UTC, sakshi006 requested changes
Added some styling changes.

2022-02-02 13:35 UTC, merged